### ISSUE TITLE
Incorrect dirname on pathes having .

### ISSUE THREAD

**Issue by is-blackhole** [matthiasmullie/path-converter#1]
Hi, thanks for your work, it saves me :)

I found an issue, I have  $to path like /var/www/mysite.com/assets/some_random_folder_name/ Converter::dirname will assume its a file because of  mysite.com in path and because folder doesnt exists at this moment (will be created later)
I think this can resolve:

``` php
        // has a dot in the name, likely a file
        if (preg_match('/(^\/).*\..*$/', basename($path)) !== 0) {
            return dirname($path);
        }
```

**Comment by matthiasmullie** [comment]
Hi @is-blackhole 

Thanks for the bug report (and suggestion for the fix!)
I've just pushed b1e31c51e8c207ad6114f5b4ac4e652bc936c380. I'm about to release a new version with that fix.
