### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by rgarciacostex** [matthiasmullie/path-converter#12]
PHP Fatal error:  Uncaught Error: Interface 'WP_Rocket\Dependencies\PathConverter\ConverterInterface' not found in /home/site/public_html/wp-content/plugins/wp-rocket/inc/Dependencies/PathConverter/Converter.php:19
Stack trace:
#0 /home/site/public_html/wp-content/plugins/seo-by-rank-math-pro/vendor/composer/ClassLoader.php(444): include()
#1 /home/site/public_html/wp-content/plugins/seo-by-rank-math-pro/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/site/...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('WP_Rocket\\Depen...')
#3 /home/site/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/CSSTrait.php(79): spl_autoload_call('WP_Rocket\\Depen...')
#4 /home/site/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/CSSTrait.php(53): WP_Rocket\Engine\Optimization\Minify\CSS\Combine->get_converter('/home/site/...', '/home/site/...')
#5 /home/site/public_html/wp-content/plugins/wp-rocket/inc/Engine/Optimization/Minify/CSS in /home/site/public_html/wp-content/plugins/wp-rocket/inc/Dependencies/PathConverter/Converter.php on line 19

**Comment by matthiasmullie** [comment]
Sounds like an file inclusion/autoloader issue
