### ISSUE TITLE
Open_basedir warning when $from and $to are empty

### ISSUE THREAD

**Issue by remyperona** [matthiasmullie/path-converter#2]
This issue seems to be specific with some server configurations, but I could replicate it on several ones.

when `$from` and `$to` are empty (because the source in the Minify library is CSS code directly and there is no target path set), `realpath()`, `is_file()` and `is_dir()` seems to default to the current directory, which might be the resolved path and not the one expected by the PHP configuration.

Below is an example of the warning I get.

```
PHP Warning:  realpath(): open_basedir restriction in effect. File(/var/www/etc/website) is not within the allowed path(s): (/var/www/website) in /var/www/website/vendor/matthiasmullie/path-converter/src/Converter.php on line 47
PHP Warning:  realpath(): open_basedir restriction in effect. File(/var/www/etc/website) is not within the allowed path(s): (/var/www/website) in /var/www/website/vendor/matthiasmullie/path-converter/src/Converter.php on line 48
PHP Warning:  is_file(): open_basedir restriction in effect. File(/var/www/etc/website/) is not within the allowed path(s): (/var/www/website) in /var/www/website/vendor/matthiasmullie/path-converter/src/Converter.php on line 172
PHP Warning:  is_dir(): open_basedir restriction in effect. File(/var/www/etc/website/) is not within the allowed path(s): (/var/www/website) in /var/www/website/vendor/matthiasmullie/path-converter/src/Converter.php on line 176
```

Here is another on a different server

```[warn] mod_fcgid: stderr: PHP Warning: is_file(): open_basedir restriction in effect. File(/var/www/cgi-bin/cgi_wrapper/) is not within the allowed path(s): (/var/www/vhosts/website.com/:/tmp/) in /home/vhosts/website.com/httpdocs/vendor/matthiasmullie/path-converter/src/Converter.php on line 172```

I guess possible solutions would be to suppress errors for those functions, or to check if the variables are empty before doing anything else.

**Comment by matthiasmullie** [comment]
Thanks for the PR! Merged.
