### ISSUE TITLE
missing "../"

### ISSUE THREAD

**Issue by vzz3** [matthiasmullie/path-converter#4]
Example:

`public function __construct($from, $to)` of `MatthiasMullie\PathConverter\Converter` is called with
```
$from = "typo3temp/assets/compressed/../../../typo3conf/ext/user_merkl/Resources/Public/Fonts/webfontkit-rotissanser/stylesheet.css"
$to = "typo3temp/assets/compressed/merged-abce7d875ee92a78bd5e1871ef774fbe.css"
```
wich result in an object with the following member variables:
```
$this->from = "typo3conf/ext/user_merkl/Resources/Public/Fonts/webfontkit-rotissanser"
$this->to = "typo3temp/assets/compressed" 
```

now the method `public function convert($path)` is called with `$path = "rotissanser-webfont.eot"`. This method cal returns:
`"../../typo3conf/ext/user_merkl/Resources/Public/Fonts/webfontkit-rotissanser/rotissanser-webfont.eot"`
which is wrong! The correct result should by:
`"../../../typo3conf/ext/user_merkl/Resources/Public/Fonts/webfontkit-rotissanser/rotissanser-webfont.eot"`

In order to fix this problem I replaced the line 158:
`$to = str_repeat('../', mb_substr_count($to, '/'));`
with this line:
`$to = str_repeat('../', count(explode('/', $to)));`

**Comment by vzz3** [comment]
A better solution that can handle relative and absolut input paths could be:
```
$sourcePathSteps = count(explode('/', $to));
if($to[0] == '/') {
	$sourcePathSteps--;
}
$to = str_repeat('../', $sourcePathSteps);
```

**Comment by matthiasmullie** [comment]
Hey @vzz3 

Thanks for reporting the issue & apologies this took awhile for me to get to :)
Fix has just been submitted & new release is coming up!
