### ISSUE TITLE
Wrong final path when the original paths contains current directory indicator

### ISSUE THREAD

**Issue by remyperona** [matthiasmullie/path-converter#6]
The method `normalize` doesn't take into account the case where the original path contains the current directory indicator `.`

This results into incorrect path returned by the `normalize`method, for example:
original: `./../images/header-section/HeroImage.jpg`
expected: `../images/header-section/HeroImage.jpg`
result : `images/header-section/HeroImage.jpg`

original: `themes/styles/./../images/header-section/HeroImage.jpg`
expected: `themes/images/header-section/HeroImage.jpg`
result: `themes/styles/images/header-section/HeroImage.jpg`

**Comment by matthiasmullie** [comment]
Fixed with https://github.com/matthiasmullie/path-converter/pull/7 - thanks!
