### ISSUE TITLE
Consider converting to absolute path?

### ISSUE THREAD

**Issue by walisc** [matthiasmullie/path-converter#8]
There are cases when you request a minified (i.e css) file in a none direct way (eg. `/get_resource/css_main` where `get_resource` is a function endpoint). Since the path-convertor converters path based on actual locations, when the above request is made it resolved incorrectly. ie

```
from_path: 'resource/css/all.css'
to_path: 'resouces/minified/minified.css'
relative_path: ../css/webfont.woff
```
And if get minified.css using the request url above,  the relative path will become `/get_resource/css/webfont.woff` which is wrong.

This could be avoided if we could have an option of converting to an absolute path (based on a root)

**Comment by matthiasmullie** [comment]
~~Fixed with https://github.com/matthiasmullie/path-converter/pull/7 - thanks!~~
^ That was meant for another issue

**Comment by matthiasmullie** [comment]
The constructor accepts a 3rd argument for $root. Setting that the the correct root should do exactly what you want & eliminate any guesswork based on current directory.
